spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 547846374659-dd33a3kdvp4al352cergjdr4qvavrehf.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/oauth2/callback/google
            scope:
              - profile
              - email
          naver:
            client-id: _Wy2PO87WZZDXjbLEoaG
            client-secret: 1Eb4yGNhp1
            redirect-uri: http://localhost:8080/oauth2/callback/naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - nickname
              - email
              - profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
app:
  auth:
    token-secret: 9742F6BEC9F62596C2FFEFF9FA0B9E39303554C06F94AB9B85C8090E3EE87F3CF0BE4BFA244C625E3F691321F9CFF38C228C4C3C91105C23919B16F7E40BE4EC
    access-token-expiration-msec: 3600000
    refresh-token-expiration-msec: 1209600000
  cors:
    allowed-origins: http://localhost:3000, http://localhost:8080